# markdown
markdown: kramdown
kramdown:
  extensions: ["superscript","tables","with_toc_data","strikethrough","smart"]
highlighter: rouge

plugins:
  - jemoji
  - jekyll-redirect-from

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# Site metadata
name: "Emerging Citizen Technology"
description: "Just a fraction of federal emerging citizen technology."
baseurl: ""

# Google Analytics
google_analytics: UA—110413123-1

# Uncomment the following line for localhost development at http://127.0.0.1:4000/software/
# baseurl: /software

# GitHub information
org_name: gsa
repo_name: emerging-technology-atlas
branch: master

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: "Home"
  url: /
- text: "Take Action"
  sub_nav:
  - text: "Connect"
    url: /connect/
  - text: "Contribute"
    url: /howto/
  - text: "Dan Raudonis"
    url: /updates/
- text: "About GSA Emerging Citizen Technology Office"
  sub_nav:
  - text: "What We Do"
    url: /emergingcitizentech/
  - text: "Participating Agencies"
    url: /participatingagencies/
- text: "Our Emerging Technologies"
  sub_nav:
  - text: "Artificial Intelligence"
    url: /artificial-intelligence/
  - text: "Blockchain"
    url: /blockchain/
  - text: "Virtual/Augmented Reality"
    url: /virtual-reality/
  - text: "Social Technology"
    url: /Socialgov/
- text: "Our Inter-Agency Initiatives"
  sub_nav:
  - text: "Technology Modernization Fund"
    url: /TMF/
  - text: "Open Data for AI"
    url: /OpenDataforAI/
  - text: "100 Federal Emerging Tech Leaders Initiative"
    url: /100Leaders/
  - text: "Academic Research Outreach"
    url: /AcademicOutreach/
  - text: "Venture Capital Advisory Group"
    url: /VentureCapital/
  - text: "Training and Education"
    url: /Training/
- text: "Our Resources"
  sub_nav:
  - text: "Meeting Notes & Action Items"
    url: /meeting-notes/
  - text: "Calendar"
    url: /calendar/
